### PR TITLE
Correcting a bug introduced in fbdbe6eff32ae5c01a6ea707a4e908c0cb1a4ebe

### PR DESCRIPTION
**Pull request by nmalzieu**
The diff is not clear but the fix is actually really simple
In https://github.com/nfc-tools/libnfc/commit/fbdbe6eff32ae5c01a6ea707a4e908c0cb1a4ebe#diff-6e1237eedf36b29193c30b63cf243259R449 a new check was added line 449 before printing an authentication error but the closing bracket `}` was not added.

The result is `is_first_block` is not closed and the rest of the code is not executed so only 1st blocks of each sector was written!

By checking the files directly it's really simple to see.

### CODE REVIEW

**Comment by nmalzieu** [comment]
@quantum-x I think your commit introduced the bug, if you can have a look 😃

**Comment by quantum-x** [comment]
Unless I'm mistaken, my commit was OK, it looks like it was the merge that caused the issue?
https://github.com/toyfoundry/libnfc/blame/c1e466d4a8900ba04d569fe7f268c1d942591679/utils/nfc-mfclassic.c#L443

**Comment by nmalzieu** [comment]
@quantum-x ah, maybe! I don't have access to your link though. Sorry about that :)
Do you agree with the fix?

**Comment by AdamLaurie** [comment]
@nmalzieu please confirm this is still an issue and provide test instructions to demonstrate problem - i have been unable to reproduce any block writing error. thanks!

**Comment by AdamLaurie** [comment]
I believe this is now fixed. Thanks @nmalzieu for the initial report.

**Pull request closed without merging**
