### PR TITLE
Add travis config file

### PR DESCRIPTION
**Pull request by xantares**
travis continuous integration service must be enabled from repo settings

### CODE REVIEW

**Comment by smortex** [comment]
Doesn't it make sense to install cutter as a dependency and run the test suite shipped with libnfc?

I understand that checking that the software builds is a good start (`-Wall -Wextra -Werror -pedantic` may be advisable in such a case however), but building successfully a broken software does not really help I think.

**Comment by xantares** [comment]
I know it's not getting better than that

**Comment by neomilium** [comment]
Any improvement ?

**Comment by neomilium** [comment]
Thanks. Hope someone will improve it later.

**Pull request merged**
