### PR TITLE
Added NEWS and README with links to md files

### PR DESCRIPTION
**Pull request by frankmorgner**
NEWS and README are mandatory for autoconf. Fixes problem introduced in
b1a81b385ddabb704b4cea64fda56abb9928c3c3

The current status can be checked here https://travis-ci.org/frankmorgner/vsmartcard/jobs/122279341#L2087

### CODE REVIEW

**Comment by smortex** [comment]
Wouldn't it be wiser to add `foreign` to `AM_INIT_AUTOMAKE`?.

**Comment by frankmorgner** [comment]
>The foreign option tells Automake that this package will not follow the GNU Standards.

Seems to be an other way to solve the issue, but I'm not the one to decide...

**Comment by hiddewie** [comment]
I saw the build failure because of my commit(s). Sorry for not checking the makefile for changes.

**Comment by frankmorgner** [comment]
No problem. Who is in charge for deciding the actual resolution? @neomilium @smortex @doegox ?

**Comment by doegox** [comment]
If @smortex solution works, I'm more in favor of it that creating phony files.

**Comment by frankmorgner** [comment]
done and fixed in #349

**Comment by oliv3r** [comment]
The applied fix in #349 is insufficient as this still fails for cmake.

CMake Error at /usr/share/cmake-3.6/Modules/CPack.cmake:423 (message):
  CPack package description file: "/home/oliver/dev/libnfc/README" could not
  be found.

@frankmorgner how does @hiddewie compile libnfc? As both automake and cmake complain loudly ...

**Comment by frankmorgner** [comment]
@oliv3r not quite true, autotools build just fine with https://github.com/nfc-tools/libnfc/pull/349 (i.e. current master)

**Pull request closed without merging**
