### PR TITLE
Allow mfultralight and mfc tools to work also with specific UID's

### PR DESCRIPTION
**Pull request by oliv3r**
This patch series does some code cleanup/fixups on a small scale, but most importantly adds the ability to specify UID's to mfc-classic and mfultralight tools to r/w a specific tag when multiple tags are insight.

### CODE REVIEW

**Comment by neomilium** [comment]
@oliv3r : Good job, thanks ! :+1:

**Comment by quantum-x** [comment]
@neomilium This is probably way too late, but it is worth noting that this patch breaks backward compatibility by adding the (unnecessary) u switch.

I propose that u/U is unnecessary, defaulting to 'standard' behavious but can be provided if required.
libnfc is used by many people in many different scenarios, shouldn't patches that break compatibility should be discussed before they're merged ?

**Comment by doegox** [comment]
@quantum-x we try to be careful regarding the libnfc itself and its API, but in our opinion the provided tools are just (useful) examples based on the libnfc and their CLI usage must not be preserved at all cost.

E.g. if you want to provide a more future-proof interface with single-letter Unix-style options + their GNU-style long-named equivalents, you're more than welcome to submit a patch.

**Comment by quantum-x** [comment]
@doegox No arguments from me based off your points.
With that said, the submitted patch introduces an optional functionality, seemily a convenience function for the author. They're definitely flags that could be made optional.

If we don't *need* to break CLI compatibility, why do it? 
Other contributors (myself included, if you look at my patch history) are able to provide non-breaking flags.

**Comment by doegox** [comment]
The current scheme to pass arguments to `nfc-mfclassic` is a list of fixed fields so if you want to add an option you have to add a field. Only last field(s) can be optional and this is already the case for `[<keys.mfd> [f]]`. The only proper way to avoid that is to pass optional arguments as most CLI do, this is what I proposed in my answer.

**Comment by quantum-x** [comment]
Seems like a great idea. 
Perhaps that requirement should have been / should be part of the original PR to avoid headaches for other users.

@oliv3r is this something that you would consider implementing?

**Pull request merged**
