### PR TITLE
Adding support for UL Gen 2 Badges

### PR DESCRIPTION
**Pull request by quantum-x**
Adds support for Magic MF Ultralight Gen 2 tags.
These tags are unlocked with the 'standard' 0x40 / 0x43 commands.

Once unlocked, the badge is written as per normal.

### CODE REVIEW

**Comment by AdamLaurie** [comment]
Verified - successfully cloned a m/f u/l hotel key. Good job! :)

**Comment by AdamLaurie** [comment]
Actually, hold that thought. This patch appears to break writing of older cards...

**Comment by quantum-x** [comment]
@AdamLaurie Older cards as in Gen 1 UL, or vanilla UL?

**Comment by AdamLaurie** [comment]
Not sure what generation, but older magic rewriteable U/L card. I have emailed you my output.

**Comment by quantum-x** [comment]
Thanks for the catch!

Tested on Gen 1, Gen 2 and non-magic cards:

```
Gen 1
$ ./nfc-mfultralight w ul-test.dmp --full
NFC device: SCM Micro / SCL3711-NFC&RW opened
Found MIFARE Ultralight card with UID: 044e075ad42184
Writing 16 pages |................|
Done, 16 of 16 pages written (0 pages skipped).

Gen 2
$ ./nfc-mfultralight w ul-test.dmp --full
NFC device: SCM Micro / SCL3711-NFC&RW opened
Found MIFARE Ultralight card with UID: 044e075ad42184
Writing 16 pages |................|
Done, 16 of 16 pages written (0 pages skipped).

Non-magic
$ ./nfc-mfultralight w ul-test.dmp --full
NFC device: SCM Micro / SCL3711-NFC&RW opened
Found MIFARE Ultralight card with UID: 044e075ad42184
Writing 16 pages |
Unable to unlock card - are you sure the card is magic?
$
```

**Comment by AdamLaurie** [comment]
Verified now also working with my older magic cards. Thanks!

**Comment by neomilium** [comment]
Thanks @quantum-x , @AdamLaurie

**Pull request merged**
