### PR TITLE
[WIP] MFRC522 support

### PR DESCRIPTION
**Pull request by socram8888**
This is a pretty large and still WIP which adds support for the cheaper and yet pretty capable MFRC522 ICs.
This also adds some fancy features like timeouts which don't rely on hardware, and software implementations for common stuff like anticollisions and tag selects.
Note this is still WIP. Right now only "nfc-anticol" is tested to be working.

### CODE REVIEW

**Comment by socram8888** [comment]
Where and how would be the most appropiate place to put the anticollision and select code? The RC522 has no microcontroller inside so everything has to be done in software.

**Comment by neomilium** [comment]
Hi,

Put it in your driver and use it when relevant. I think there is no need to
export this at public API level.

2015-06-30 19:55 GMT+02:00 Marcos Del Sol Vives <notifications@github.com>:

> Where and how would be the most appropiate place to put the anticollision
> and select code? The RC522 has no microcontroller inside so everything has
> to be done in software.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfc-tools/libnfc/pull/300#issuecomment-117282905>.
>



-- 
Romuald

**Comment by neomilium** [comment]
RC522 is not an NFC device, but a RFID @13,56Mhz. I dont think it should be integrated into libnfc.

**Comment by xhlyuestc** [comment]
Hello, is this libnfc support for MFRC522 completed? I want to use it along with my MFRC522 device via uart. I hope you could give me some hint. my email address is xhlyuestc@gmail.com

**Comment by socram8888** [comment]
It's not. I stopped developing it after @neomilium said he wasn't interested in pushing it upstream.

**Comment by xhlyuestc** [comment]
oh, sad to know...

**Comment by ildar** [comment]
restored and fixed building: https://github.com/ildar/libnfc/tree/pull-300

**Pull request closed without merging**
