### PR TITLE
Add SCM_SCL3712 support

### PR DESCRIPTION
**Pull request by bhack**
This add SCM SCL3712 support

### CODE REVIEW

**Comment by neomilium** [comment]
Thanks!

**Comment by bhack** [comment]
Probably you can upgrade [wiki notes](http://nfc-tools.org/index.php?title=Devices_compatibility_matrix) and reply to [this forum post](http://forums.nfc-tools.org/topic/1286/scm3712-170/)

**Comment by neomilium** [comment]
Wiki is open, so feel free to upgrade it :)

2015-11-05 9:26 GMT+01:00 bhack <notifications@github.com>:

> Probably you can upgrade wiki notes
> <http://nfc-tools.org/index.php?title=Devices_compatibility_matrix> and
> reply to this forum post
> <http://forums.nfc-tools.org/topic/1286/scm3712-170/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfc-tools/libnfc/pull/323#issuecomment-153986084>.
>



-- 
Romuald

**Comment by bhack** [comment]
Mine is a sparse contribution to libnfc. So I don't want to make two other registration for the wiki and forum. If you have the time please update it.

**Comment by neomilium** [comment]
Done.


2015-11-05 10:53 GMT+01:00 bhack <notifications@github.com>:

> Mine is a sparse contribution to libnfc. So I don't want to make two other
> registration for the wiki and forum. If you have the time please update it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfc-tools/libnfc/pull/323#issuecomment-154010318>.
>



-- 
Romuald

**Pull request merged**
