### PR TITLE
add EV1 password auth to nfc-mfultralight

### PR DESCRIPTION
**Pull request by AdamLaurie**

### CODE REVIEW

**Comment by AdamLaurie** [comment]
Please hold from accepting this PR. I've realised there's a lot more to it for EV1 as they contain different sizes of data and some other niceties that need incorporating before ready for prime time! Working on it!

**Comment by AdamLaurie** [comment]
OK, I think that takes care of it. Code now determines card size before reading file data to ensure correct size as well as copying EV1 secrets so they are preserved when written back. Please go ahead and merge unless you find other issues! :)

**Comment by neomilium** [comment]
@AdamLaurie why don't you use libfreefare to handle tags ?

**Comment by doegox** [comment]
Well today the only MFUL RW tool is in libnfc, not libfreefare. And EV1 commands don't imply crypto so they are easily added to the existing nfc-mfultralight.
What could make sense is to migrate all nfc-mf* to libfreefare and mifare-* but it's more effort than moving a few files around, ideally they should be rewritten to use the framework of libfreefare...
BTW in the MFUL family there is also a recent pull req on libfreefare for NTAG, not yet accepted, I didn't test it yet : https://github.com/nfc-tools/libfreefare/pull/53/files

**Comment by AdamLaurie** [comment]
@neomilium I haven't used libfreefare for anything other than the occasional test so not really up to date with it's capabilities, but at @doegox said, the tool already exists in libnfc so it makes sense to keep it up to date. At some point I may possibly look at  libfreefare and I'll also even bring my own readmifareultra.py (RFIDIOt) script in to line! :)

**Comment by AdamLaurie** [comment]
BTW if you're unable to merge because you can't test, just ping me an address offline and i'll send you some sample cards. :)

**Comment by doegox** [comment]
ha sorry I've a couple of them thank you, I just forgot this task on my todo :grin:

**Comment by doegox** [comment]
Hi Adam
I merged it and added a couple of commits on top.
Please check.
I guess you have only MF0UL11 cards, and I have only MF0UL21 cards...

**Comment by AdamLaurie** [comment]
Works for me - yes, I only have MF0UL11 and some MF0UL21 on order. Was there a problem with them?

**Comment by doegox** [comment]
Yes struct was too short (missing lock bytes) and reading was overwriting vars out of struct boundaries, killing uiReadPages. Moreover their size is not a multiple of 16b, so I had to adapt the read loop to cope with last read shorter than 4 pages.
Because of the lock bytes page, config struct gets misaligned. To keep it simple I added new config structs specific to MF0UL21 rather than introducing a quarter of block behind.

**Comment by doegox** [comment]
When you think of it, memory layout of MF0UL21 is pretty horrible...

**Comment by AdamLaurie** [comment]
Ah, OK... Thanks for sorting it out! :)

**Pull request merged**
